# Generated by Django 3.2.4 on 2021-06-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('stuff', 'Stuff'), ('customer', 'Customer'), ('vendor', 'Vendor'), ('deliveryman', 'Deliveryman')], default=None, max_length=12, null=True),
        ),
    ]
